from __future__ import annotations

import json
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
Y_DIR = ROOT / "Y"
REPORT = Y_DIR / "quiz-validation-report.md"


def main() -> None:
    rows = []
    details = []
    for path in sorted(Y_DIR.glob("*quiz.html")):
        payload = read_payload(path)
        if not payload:
            continue
        questions = payload.get("questions", [])
        issues = []
        for question in questions:
            found = inspect_question(question)
            if found:
                issues.append((question.get("id"), found, question.get("stem", "")[:120]))

        answered = sum(1 for question in questions if question.get("answers"))
        provisional = sum(1 for question in questions if question.get("provisional"))
        rows.append({
            "file": path.name,
            "questions": len(questions),
            "answered": answered,
            "unanswered": len(questions) - answered,
            "provisional": provisional,
            "issues": len(issues),
        })
        if issues:
            details.append((path.name, issues[:20]))

    lines = [
        "# Y Quiz Validation Report",
        "",
        "Generated by `scripts/validate-y-quizzes.py`.",
        "",
        "| file | questions | answers present | provisional answers | unanswered | structural flags |",
        "|---|---:|---:|---:|---:|---:|",
    ]
    for row in rows:
        lines.append(f"| `{row['file']}` | {row['questions']} | {row['answered']} | {row['provisional']} | {row['unanswered']} | {row['issues']} |")

    lines.extend([
        "",
        "## Flag Meaning",
        "",
        "- `no_answer`: 정답 후보가 비어 있는 문항입니다. 현재 생성 정책상 0이어야 합니다.",
        "- `provisional answers`: 원본 정답 표시를 못 찾아 임시 정답 후보를 넣은 문항입니다.",
        "- `options<2`: 주관식/단답형 또는 보기 분리 실패 가능성이 있는 문항입니다.",
        "- `options>7`: 복수선택/순서배열 문항이거나 보기 병합 오류 가능성이 있는 문항입니다.",
        "- `very_long_option`: 보기 하나에 다른 문항 또는 긴 설명이 섞였을 가능성이 있습니다.",
        "- `short_stem`: 문항 본문이 너무 짧아 앞 문장 누락 가능성이 있습니다.",
        "",
        "## Flagged Samples",
        "",
    ])

    for file_name, issues in details:
        lines.append(f"### `{file_name}`")
        for question_id, found, stem in issues:
            lines.append(f"- Q{question_id}: {', '.join(found)} — {stem}")
        lines.append("")

    REPORT.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
    print(REPORT)


def read_payload(path: Path) -> dict | None:
    text = path.read_text(encoding="utf-8")
    match = re.search(r"const examData = (.*?);\n    const questions", text, re.S)
    if match:
        return json.loads(match.group(1))
    legacy = re.search(r"const questions\s*=\s*(\[.*?\]);.*?const state", text, re.S)
    if not legacy:
        return None
    questions_text = re.sub(r"(\n\s*)([A-Za-z_]\w*):", r'\1"\2":', legacy.group(1))
    return {"questions": json.loads(questions_text)}


def inspect_question(question: dict) -> list[str]:
    issues = []
    stem = str(question.get("stem", ""))
    options = question.get("options", [])
    if len(options) < 2:
        issues.append("options<2")
    if len(options) > 7:
        issues.append("options>7")
    if len(stem.strip()) < 8:
        issues.append("short_stem")
    if not question.get("answers"):
        issues.append("no_answer")
    if any(len(str(option)) > 180 for option in options):
        issues.append("very_long_option")
    if has_section_noise(stem) or any(has_section_noise(str(option)) for option in options):
        issues.append("section_noise")
    return issues


def has_section_noise(value: str) -> bool:
    stripped = value.strip()
    if "+문항" in stripped or "+ 문항" in stripped:
        return True
    return ("문제" in stripped or "문항" in stripped) and (stripped.startswith("<") or stripped.startswith("["))


if __name__ == "__main__":
    main()
